new test vectors for testing puk reverse sigs
keybase/keybase-test-vectors pull request #7
Opened 2017-07-14 17:44 UTC by modalduality

2017-07-14 18:09 UTC, maxtaco requested changes
This looks great, but a few small changes.

2017-07-14 18:09 UTC, maxtaco commented on chains/bad_per_user_key_reverse_sig.json
> +      "undefined" : "0121a075a79ff4f884fe1801bf0151803a9b99960d6d642d10d4ae21c6d3f7d0ea2f0a",
something might be up here

2017-07-14 18:09 UTC, maxtaco commented on chains/inputs/bad_per_user_key_reverse_sig.iced
> +          obj.body.per_user_key.reverse_sig = 'a' + obj.body.per_user_key.reverse_sig[1..]
instead of corrupting the sig, can you corrupt the thing the sig is computed over?  that would be more interesting.

2017-07-17 22:39 UTC, modalduality commented
@maxtaco This now corrupts the message that the signature is over and recomputes the signature instead of the signature itself. (and both positive and negative tests pass on client)

I couldn't figure out the problem with the label_kids, will have to look more into it tomorrow.

2017-07-18 14:22 UTC, maxtaco approved these changes

2017-07-18 14:33 UTC, merged